name: hanon
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.1
  expansion_tile_card: ^3.0.0
  table_calendar: ^3.0.9
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.0.15
  local_auth: ^2.1.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  file_picker: ^10.1.9
  gif: ^2.3.0
  mime: ^2.0.0
  http_parser: ^4.1.2
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  cloud_firestore: ^5.6.8
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  confetti: ^0.8.0
  google_mlkit_face_detection: ^0.13.1
  camera: ^0.11.1
  image: ^4.5.4
  flutter_staggered_animations: ^1.1.1
  tflite_flutter: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/banner.png
    - assets/l logo.png
    - assets/attendance.png
    - assets/leave.png
    - assets/log.png
    - assets/panic.png
    - assets/logout.png
    - assets/biometric.png
    - assets/no_profile.jpg
    - assets/animations/blue bg.png
    - assets/animations/blue s bg.png
    - assets/thank you.gif
    - assets/animations/girl eating.gif
    - assets/animations/girl sleep.gif
    - assets/animations/girl work.gif
    - assets/animations/boy eating.gif
    - assets/animations/boy sleep.gif
    - assets/animations/boy work.gif
    - assets/animations/pink bg.png
    - assets/animations/pink s bg.png
    - assets/birthday.png
    - assets/general.png
    - assets/visitor.png
    - assets/animations/boy water.gif
    - assets/animations/boy workout.gif
    - assets/animations/girl leisure.gif
    - assets/animations/girl workout.gif
    - assets/animations/girl water.gif
    - assets/animations/boy leisure.gif
    - assets/animations/cake img.gif
    - assets/approver.png
    - assets/pending.png
    - assets/rejected.png
    - assets/in punch.png
    - assets/out punch.png







  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
